name: Bug Report
description: Report a bug
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
        Please make sure to be as specific as possible in your description and title.
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Please check the following before filing a bug report.
      options:
        - label: This bug is in DelphiLint, not SonarQube or the Delphi IDE.
          required: true
        - label: This bug has not already been reported.
          required: true
        - label: >
            This bug is not a problem related to analysis quality (e.g. parsing errors, false positive issues), which
            should be raised on the [SonarDelphi repository](https://github.com/integrated-application-development/sonar-delphi/issues).
          required: true
  - type: input
    attributes:
      label: Delphi IDE version
      description: >
        Specify your Delphi IDE version and edition.
      placeholder: "Delphi 12 Version 29.0.51511.6924 (Professional)"
    validations:
      required: true
  - type: input
    attributes:
      label: DelphiLint version
      description: >
        Specify your DelphiLint version.
        If you use a development build, please test if your issue is reproducible in a release version too.
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: SonarDelphi version
      description: >
        Specify the SonarDelphi version DelphiLint is using.

        In Standalone mode, this can be seen at DelphiLint > Settings > SonarDelphi version configuration.

        In Connected mode, this is usually the version of SonarDelphi on your SonarQube instance.
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: SonarQube version
      description: >
        If relevant, specify the SonarQube version you are using.
      placeholder: "10.0"
  - type: textarea
    attributes:
      label: Issue description
      description: |
        Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Provide steps that can be used to reproduce the issue. Issues that are not reproducible are
        unlikely to be resolved. If you include a minimal Delphi project below, you can detail what to look for here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Delphi code exhibiting the issue
      description: |
        If applicable, a zip file of a minimal Delphi project that exhibits the issue when scanned.
        Drag and drop a ZIP archive to upload it.