name: Inquiry
description: Ask a question
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for inquiring about DelphiLint!
        Please make sure to be as specific as possible in your description and title.
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Please check the following before making an inquiry.
      options:
        - label: This question has not already been answered.
          required: true
  - type: textarea
    attributes:
      label: Inquiry
      description: |
        What's your question?
    validations:
      required: true