name: Build

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/build.yml'
      - 'server/**'
      - 'companion/delphilint-vscode/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'server/**'
      - 'companion/delphilint-vscode/**'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Run Maven Verify
        working-directory: ./server
        run: mvn --batch-mode --update-snapshots verify
  companion-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Compile Extension
        working-directory: ./companion/delphilint-vscode
        run: npm install && npm run compile